###
apiPage=
$doctype()$
<html>
  <head>
    <title>$pagetitle()$ Scrive API</title>
    <meta name="description" content="$_apiPageMetaDescription()$" />
    $standardHeaderContents()$
  </head>
  $standardBodyWithQueryCol(unwrappedbody=apiPageContents())$
</html>
###
apiPageContents=
<div class="nicetext">
  <h1>Scrive API</h1>
  <br />
  <p>
    The Scrive API brings the Scrive signature solution into the
    enterprise. The Scrive API allows our clients to develop
    integrations customized to their workflows. <strong>Close deals
    faster</strong> with the Scrive API.
  </p>
  <br />
  <p>
    Tap into a powerful signing solution. The Scrive API is the
    fastest way to incorporate <strong>electronic contract delivery,
    management, and signing</strong> into your software. Scrive prides
    itself on developing an <strong>industry-standard and
    secure</strong> API, capable of meeting the demands of the large
    enterprise.
  </p>
  <br />
  <p>
    Eliminate costly paper-based contracts and tenders. Deliver your
    contracts directly to the email inbox and see them signed within
    minutes.
  </p>
  <br />
  <h2> Some uses for the Scrive API: </h2>
  <br />
  <ul>
    <li>Leverage your existing document assets</li>
    <li>Fit document sending and signing into your negotiation and
    approval workflows</li>
    <li>Fill in contact details automatically from your CRM</li>
  </ul>
  <br />
  <h2>Signing</h2>
  <br />
  <p>
    Our customers enjoy document signing times measured
    in <strong>hours instead of days or weeks.</strong>
  </p>
  <br />
  <p>
    The Scrive signing solution has been <strong>thoroughly legally
    researched</strong>. We have tuned the emails, web pages, and PDF
    text to "step out of the way" and provide a neutral ground for
    your business deals yet provide the legal features necessary for a
    valid electronic signature. As our integration partner, you can
    customize all emails and signing pages to <strong>reflect your
    brand identity</strong>.
  </p>
  <br />
  <p>
    The integration uses Scrive's specially developed document seal,
    containing <strong>legal evidence</strong> of the validity of the
    signatures. Any questions as to the legality of the agreement can
    deal specifically with the content of the seal. We believe that
    the contents of the seal are better evidence than an ink-on-paper
    signature.
  </p>
  <br />
  <p>
    The final, signed contract is digitally signed by a third party to
    ensure that it will never change without your knowledge. Finally,
    the contract is <strong>emailed to all parties involved</strong>,
    so everyone has their own copy of the terms of the agreement. The
    document is also stored on our servers in an archive.
  </p>
  <br />
  <h2>Document Creation</h2>
  <br />
  <p>
    Any valid PDF may be used as an electronic contract with
    Scrive. It could be created with Microsoft Word or any other
    system. The API can <strong>create a document</strong> and assign
    the contact details to the signatories.
  </p>
  <br />
  <p>
    The Scrive API allows you to integrate with <strong>your existing
    CMS</strong> and word processing solution.
  </p>
  <br />
  <h2>Signing Management</h2>
  <br />
  <p>
    With the Scrive API, you can know exactly where each document is
    in the signing process. The integration can <strong>track these
    details</strong>:
  </p>
  <br />
  <ul>
    <li>Has the invitation been delivered?</li>
    <li>Has the email been opened?</li>
    <li>Has the party opened the document to view it?</li>
    <li>Has the party signed or rejected?</li>
  </ul>
  <br />
  <h2>Document Archive</h2>
  <br />
  <p>
    When the signing process is completed, the document is stored on our
    <strong>secure server</strong>. The Scrive API gives you access to
    these documents. You decide where they are stored. Download them
    to your own systems or leave them on Scrive.
  </p>
  <br />
  <h2>Technical Details</h2>
  <br />
  <p>
    You can find technical documentation related to the all of our API
    offerings <a href="http://api.scrive.com/">here</a>.
  </p>
  <br />
  <p>
    The upcoming Scrive API follows standard HTTP REST best-practices,
    making it <strong>simple to integrate</strong> with any system,
    regardless of programming language.
  </p>
  <br />
  <p>
    Integration partners can manage multiple authentication tokens
    which can be revoked independently to accommodate a variety of
    security policies.
  </p>

</div>
###
