###
clientsPage=
    $doctype()$
    <html>
      <head>
        <title>$pagetitle()$ | Kunder</title>
        <meta name="description" content="Signera och arkivera dina avtal elektroniskt. Våra kunder och våra kunders kunder älskar enkelheten." />
        $standardHeaderContents()$
      </head>
      <body>
         $bodystart()$
         <div class="left-column">
           $queryColumn()$
         </div>
         <div class="right-column">
           <div class="mainContainer">
             $clientsPageContents()$
           </div>
         </div>
         $bodyend()$ 
      </body>
    </html>
###
clientsPageContents=
					<div class="opaque wide box smaller">
						<h1>Kundutlåtanden om SkrivaPå</h1>
						<p>SkrivaPå är en tjänst för att underteckna och arkivera avtal elektroniskt. Vi hjälper våra kunder att minska sina kostnader, öka sin omsättning och spara frustration. </p>
						<br />
						<p>Vi är övertygade om att våra främsta styrkor är vår förmåga att se kundens behov, vår kundnära personliga approach och vår förmåga att lösa oerhört komplexa och svåra juridiska och säkerhetsrelaterade problem på sätt som verkar enkla och tilltalande för slutkund.</p>
						<br />
						<ul class="partner-list">
							<li>
								<div class="partner-image">
									<img src="/img/goenterprise-logo.png" />
								</div>
								<h2>Go Enterprise</h2>
								<blockquote>”Processerna blir betydligt smidigare. Man sparar tid helt enkelt.”</blockquote>
								<em>- Lisa Renander och Julia Hamrin, VD och Säljchef</em>
								<p>Go Enterprise är ett ungt managementbolag där vi brinner för tillväxt, entreprenörskap och samhällsutveckling. Genom våra RIKA-koncept inspirerar vi till handlingskraft och problemlösning.
RIKA står för research, idé, koncept och action – de fyra stegen i en problemlösningsprocess.</p>
								<a href="http://www.goenterprise.se">www.goenterprise.se</a>
							</li>
							<li>
								<div class="partner-image">
									<img src="/img/accountfactory-logo.png" style="left:3px;top:3px;"/>
								</div>
								<h2>Account Factory</h2>
								<blockquote>”Skönt. Snabbare vändor med kund och man slipper arkivera papper.”</blockquote>
								<em>- Mikael Green, VD</em>
								<p>Account Factory sköter bokföringen för småföretag. Bara fasta priser och allt på webben.</p>
								<a href="http://www.accountfactory.se">www.accountfactory.se</a>
							</li>
							<li>
								<div class="partner-image">
									<img src="/img/greenhatpeople-logo.png" />
								</div>
								<h2>Green Hat People</h2>
								<blockquote>”Man har mycket bättre koll på de avtal som ingåtts. Det är grejen tycker jag.”</blockquote>
								<em>- Alexis Barnekow, Försäljningschef</em>
								<p>Green hat People genomför oslagbara teambuildingaktiviteter i form av mobilstyrda spel där omgivningen utgör spelplanen. De finns representerade i hela Sverige och genomför teambuilding över hela Europa.</p>
								<a href="http://www.greenhatpeople.se">www.greenhatpeople.se</a>
							</li>
							<li>
								<div class="partner-image">
									<img src="/img/eventbook-logo.png" />
								</div>
								<h2>EventBook</h2>
								<blockquote>"Smart lösning."</blockquote>
								<em>- Christoffer Lindquist, VD</em>
								<p>Din partner för konferens, kick-off och företagsresor.</p>
								<a href="http://www.eventbook.se">www.eventbook.se</a>
							</li>
                                                        <li>
								<div class="partner-image">
									<img src="/img/accenture-logo.png" />
								</div>
								<h2>Accenture Management Consulting</h2>
								<h3>"Tjänsten är väldigt smidig och det visar verkligen hur mycket man kan effektivisera avtalsprocessen."</h3>
								<em>- Ola Brundin, Accenture Management Consulting</em>
								<a href="http://www.eventbook.se">www.eventbook.se</a>
							</li>
						</ul>
					</div>
###
