###
featuresPage=
$doctype()$
<html>
  <head>
    <title>$pagetitle()$ Scrive Features</title>
    <meta name="description" content="$_featuresPageMetaDescription()$" />
    $standardHeaderContents()$
  </head>
  $standardBody(unwrappedbody=featuresPageContents())$
</html>
###
featuresPageContents=
  <div class="big-pp-container">
    <table>
      <thead>
        <tr>
          $_priceplanPagePriceplanTop()$
        </tr>
      </thead>
      <tbody>
        <tr class="odd-row">$_priceplanPageTableRow001()$
        </tr>
        <tr>$_priceplanPageTableRow002()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow003()$
        </tr>
        <tr>$_priceplanPageTableRow004()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow005()$
        </tr>
        <tr>$_priceplanPageTableRow006()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow007()$
        </tr>
        <tr>$_priceplanPageTableRow008()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow009()$
        </tr>
        <tr>$_priceplanPageTableRow010()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow011()$
        </tr>
        <tr>$_priceplanPageTableRow012()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow013()$
        </tr>
        <tr>$_priceplanPageTableRow014()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow015()$
        </tr>
        <tr>$_priceplanPageTableRow016()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow017()$
        </tr>
        <tr>$_priceplanPageTableRow018()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow019()$
        </tr>
        <tr>$_priceplanPageTableRow020()$
        </tr>
        <tr class="odd-row">$_priceplanPageTableRow021()$
        </tr>
      </tbody>
    </table>
  </div>
###
