###
scrivebymailPage=
$doctype()$
<html>
  <head>
    <title>$pagetitle()$ Scrive by Mail</title>
    <meta name="description" content="$_scrivebymailPageMetaDescription()$" />
    $standardHeaderContents()$
  </head>
  $standardBodyWithQueryCol(unwrappedbody=scrivebymailPageContents())$
</html>
###
scrivebymailPageContents=
<div class="nicetext">
  <h1>Scrive by Mail</h1>
  <br />
  <p>
    Send contracts simply and quickly without leaving your
    Inbox. <em>Scrive by Mail</em> makes sending an order as easy as
    sending an email.
  </p>
  <br />
  <p>
    Built on the same, powerful signing solution as the rest of
    Scrive, Scrive by Mail lets you send a document to be signed by
    multiple parties in an intuitive and straightforward manner. This
    is by far the easiest way to send a contract from your smartphone.
  </p>
  <br />
  <p>
    Simply address an email to our system, attach the PDF document,
    and type the details of the signatories into the email
    message. Our system will receive it, send the document, put a copy
    in your archive, and send you a confirmation email.
  </p>
  <br />
  <p>
    Later, when everyone has signed, you will be notified by
    email. You can then review the signatures and give final approval
    of the contract.
  </p>
  <br />
  <p>
    Imagine sending a sales contract from your phone as you leave the
    meeting! It could be signed before you arrive back at the office.
  </p>

</div>
###
