###
sitemapPage=
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
      http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- created with Free Online Sitemap Generator www.xml-sitemaps.com -->

$locales:{locale|
<url>
  <loc>$hostpart$$locale.linkhome$</loc>
  <changefreq>daily</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>$hostpart$$locale.linkpartners$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>$hostpart$$locale.linkpriceplan$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>$hostpart$$locale.linksecurity$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>$hostpart$$locale.linklegal$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>$hostpart$$locale.linkprivacypolicy$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>$hostpart$$locale.linkterms$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>$hostpart$$locale.linkabout$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>$hostpart$$locale.linkclients$</loc>
  <changefreq>daily</changefreq>
  <priority>0.80</priority>
</url>
}$
</urlset>
        $if(production)$
        <!-- Snoobi code tracking code -->
            <script type="text/javascript">
            var psSite = "8d72086524";
            var peJsHost = "https://";
            document.write(unescape("%3Cscript src='https://tr.prospecteye.com/track.js' type='text/javascript'%3E%3C/script%3E"));
            </script>
            <noscript><img src="https://tr.prospecteye.com/?id=8d72086524" style="border:0;display:none;"/></noscript>
       <!-- End of snoobi -->
       $endif$
###
