#!/bin/bash -xe

# ASSUMES file _build/kontrakcja.tar.gz exists
# TAKES OPTIONAL ARGUMENT to use as server, default is dev@dev-c-1.scrive.lan

if [ $# -eq 0 ]
  then
    SERVER=dev@dev-c-1.scrive.lan
elif [[ $1 = *[!\ ]* ]]
  then
    SERVER=$1
else
    echo "Could not read param"
    exit 1
fi

ssh $SERVER bash -xe -s <<EOF

rm -f kontrakcja.tar.gz

rm -rf kontrakcja_old

EOF

# Copy deployment .tar.gz generated by Shake
scp _build/kontrakcja.tar.gz $SERVER:

# Deploy new build
ssh $SERVER bash -xe -s <<EOF

mkdir kontrakcja_new

mv kontrakcja.tar.gz kontrakcja_new/

cd kontrakcja_new

tar xvf kontrakcja.tar.gz

cd -

supervisorctl stop dev-cron dev-messenger dev-mailer dev

mv kontrakcja kontrakcja_old

mv kontrakcja_new kontrakcja

cp conf/*.conf kontrakcja/

cd kontrakcja

./dist/build/kontrakcja-migrate/kontrakcja-migrate

rsync -avz -e ssh --delete /home/dev/kontrakcja/frontend/dist/ /srv/dev.scrive.com

chcon -Rt httpd_sys_content_t /srv/dev.scrive.com

supervisorctl start dev-cron dev-messenger dev-mailer dev

sudo /home/dev/kontrakcja/build-scripts/deployDevNginxRules.sh

EOF
