---
post:
  summary: Delete User Group Settings

  tags:
    - User Group

  description: |
    > For examples of the JSON output, see
    > [View User Group Settings](#view-user-group-settings).

    This endpoint is used to delete a given User Group's `settings` object. This
    will cause the settings to be inherited rather than the User Group having
    its own dedicated settings object.

    As such, calling delete on a User Group that already inherits will result
    in no operation being performed. Also, attempting to delete the settings
    object of a root User Group will result in an error.

    For more details on inheritance, see [View User Group Settings](#view-user-group-settings).

  parameters:
    - name: user_group_id
      in: path
      type: integer
      description: |
        The ID of the User Group whose `settings` object you wish to delete
      required: true
    - name: include-inheritable
      in: formData
      type: boolean
      description: |
        Set to `true` to see a preview of which
        values can be inherited from an ancestor User Group.
      required: false

  responses:
    200:
      $ref: ../../scrive_api.yaml#/definitions/UserGroupSettings
    403:
      description: |
        Insufficient Permissions error (this means that either no User Group
        exists with this ID or that you do not have permission to view it)
