---
post:
  summary: Delete User Group Settings

  tags:
    - User Group

  description: |
    > For examples of the JSON output, see details of "View User Group
    > Settings".

    This endpoint is used to delete a given User Group's `settings` object. This
    will cause the settings to be inherited rather than the User Group having
    its own dedicated settings object.

    As such, calling delete on a User Group that already inherits will result
    in no operation being performed. Also, attempting to delete the settings
    object of a root User Group will result in an error.

    Inheritance works as follows:

    Root User Groups (i.e. those who are not children of other User Groups) may
    not inherit since there are no ancestors to inherit from.

    A child User Group may inherit or have its own dedicated object. In the case
    that a User Group chooses to inherit the `settings` object, then that User
    Group will inherit from the closest direct ancestor with its own
    `settings` object. Since root User Groups cannot inherit, there will
    always be an ancestor from which a child can inherit.

    If you would like to see what a User Group _would_ inherit then you can
    append `?include-inheritable` to the URL when making the call. This will add
    extra `inheritable_preview` subtrees to the objects which perform the
    inheritance calculation, ignoring whether or not the User Group already
    inherits.

  parameters:
    - name: user_group_id
      in: path
      type: integer
      description: |
        The ID of the User Group whose `settings` object you wish to delete
      required: true
    - name: include-inheritable
      in: query
      type: boolean
      description: |
        Append `?include-inheritable` to the URL to see a preview of which
        values can be inherited from an ancestor User Group.
      required: false

  responses:
    200:
      $ref: ../../scrive_api.yaml#/definitions/UserGroupSettings
    403:
      description: |
        Insufficient Permissions error (this means that either no User Group
        exists with this ID or that you do not have permission to view it)
