#!/usr/bin/bash

cd /home/prod/kontrakcja/reporting/BI
echo "Changing working dir" $(pwd)

DBCXN=$(/usr/local/bin/jq -r '.database' < /home/prod/kontrakcja/kontrakcja.conf)

FROM=$(date +"%Y%m%d" -d "1 day ago")
TO=$(date +"%Y%m%d")

time psql "$DBCXN" -v date_from=$FROM -v date_to=$TO -f invoice_stats_json.sql
time psql "$DBCXN" -f groups_for_b3.sql
time psql "$DBCXN" -f users_for_b3.sql

gzip *.json

ls *.json.gz | while read file;do
  PATH_PREFIX=$(echo $file | awk -F'_' '{print $1}')/
  PATH_SUFFIX=$(echo $file | awk -F'_' '{print $2;}' | sed 's/-/\//g')/
  s3cmd put $file s3://scrive-b3-data/core/${PATH_PREFIX}${PATH_SUFFIX}
done

rm *.json.gz
