ignore  js/tinymce_plugins/hide_toolbar.js
ignore  tiny_mce/langs
ignore  tiny_mce/plugins
ignore  tiny_mce/themes
ignore  tiny_mce/skins
ignore  libs/recurly/recurly.css
ignore  api-demo
ignore  less/branding/buttons.less
ignore  less/branding/colors.less
ignore  less/branding/elements.less
ignore  less/branding/index.less
ignore  less/branding/reset.less
ignore  less/branding/sample.less
ignore  less/branding/typography.less
ignore  less/branding/header.less
ignore  less/branding/footer.less
ignore  less/branding/containter.less
ignore  less/branding/flash.less
ignore  less/branding/modal.less
ignore  less/branding/select.less
ignore  less/branding/infotextinput.less
ignore  less/branding/tooltip.less
ignore  less/branding/checkbox.less
ignore  less/branding/contact.less
ignore  less/branding/main.less
ignore  less/designview/util.less
ignore  libs/html5shiv.js
ignore  css/fonts

set systemPage
 css css/calendar.css
 css css/colorpicker.css
 css css/jquery.mCustomScrollbar.css
 less less/tinymce.less
 less less/utils.less
 less less/branding/index.less
 less less/document-pages.less
 less less/payments.less
 less less/paymentsoutside.less
 less less/oauth.less
 less less/arrows.less
 less less/blocking.less
 less less/authorview.less
 less less/doctools.less
 less less/buttons.less
 less less/util-pages.less
 less less/lists.less
 less less/tabs.less
 less less/archive.less
 less less/account.less
 less less/companybranding.less
 less less/signaturedrawer.less
 less less/paddeviceview.less
 less less/createfromtemplate.less
 less less/designview.less
 less less/signview.less
 less less/attachmentview.less
 less less/verification.less
 less less/designview/frame.less
 less less/designview/participants.less
 less less/designview/editdocument.less
 less less/designview/documentview.less
 less less/designview/process.less
 js   libs/jquery.min.js
 js   libs/jquery-migrate.min.js
 jsx  tiny_mce/tinymce.min.js
 js   libs/jquery-ui.min.js
 js   libs/jquery.tools.min.js
 js   libs/jquery.MultiFile.js
 js   libs/jquery.hashchange.js
 js   libs/colorpicker.js
 js   libs/json2.js
 js   libs/jstz.min.js
 js   libs/underscore.js
 js   libs/backbone.js
 js   libs/jquery.form.js
 js   libs/jquery.mCustomScrollbar.concat.min.js
 js   libs/livequery.js
 js   libs/recurly.js
 js   libs/moment.min.js
 js   libs/iso8601.min.js
 js   libs/html2canvas.js
 js   libs/spin.js
 js   js/global.js
 js   js/storage.js
 js   js/utils/browserinfo.js
 js   js/utils/language.js
 js   js/utils/time.js
 js   js/utils/cookie.js
 js   js/loading.js
 js   js/promo.js
 js   js/arrows.js
 js   js/flashmessages.js
 js   js/infotextinputs.js
 js   js/buttons.js
 js   js/uploadbuttons.js
 js   js/tooltips.js
 js   js/calendar.js
 js   js/submits.js
 js   js/ajaxqueue.js
 js   js/confirmations.js
 js   js/selects.js
 js   js/login.js
 js   js/new_password.js
 js   js/account_setup.js
 js   js/accept_tos.js
 js   js/new_signup.js
 js   js/lists/action.js
 js   js/lists/sorting.js
 js   js/lists/filtering.js
 js   js/lists/paging.js
 js   js/lists/schema.js
 js   js/lists/lists.js
 js   js/tabs.js
 js   js/files.js
 js   js/process.js
 js   js/fields.js
 js   js/signatories.js
 js   js/documents.js
 js   js/takeScreenshot.js
 js   js/confirmationsWithEmails.js
 js   js/authorview/authorviewtitlebox.js
 js   js/authorview/authorsviewhistory.js
 js   js/authorview/authorviewsignatoriesattachments.js
 js   js/authorview/authorviewsignatory.js
 js   js/authorview/authorviewsignatories.js
 js   js/authorview/authorview.js
 js   js/attachmentview.js
 js   js/tasks.js
 js   js/docsignviewframes.js
 js   js/doctools/dochistory.js
 js   js/doctools/docdownload.js
 js   js/doctools/docauthorattachments.js
 js   js/doctools/docevidenceattachments.js
 js   js/signview/docsignviewinstructions.js
 js   js/signview/docsignviewsignatories.js
 js   js/signview/docsignviewextradetailssection.js
 js   js/signview/docsignviewsignsection.js
 js   js/signview/docsignviewpad.js
 js   js/signview/docsignviewattachments.js
 js   js/signview/docsignview.js
 js   js/designview/participants.js
 js   js/designview/editdocument.js
 js   js/designview/documentview.js
 js   js/designview/docdesignview.js
 js   js/designview/authoraattachmentsdesign.js
 js   js/designview/signatoryattachmentsdesignview.js
 js   js/designview/attachmentslist.js
 js   js/designview/process.js
 js   js/designview/designviewtabs.js
 js   js/mobilebankid.js
 js   js/bankid.js
 js   js/createfromtemplate/createfromtemplate.js
 js   js/csvsignatorydesign.js
 js   js/validation.js
 js   js/signaturedrawer.js
 js   js/fieldplacementview.js
 js   js/padview.js
 js   js/fileverifier.js
 js   js/payments.js
 js   js/archive/documents.js
 js   js/archive/templates.js
 js   js/archive/attachments.js
 js   js/archive/bin.js
 js   js/archive/archive.js
 js   js/admin/admin.js
 js   js/admin/companyadmin.js
 js   js/admin/useradmin.js
 js   js/admin/documentadmin.js
 js   js/admin/csvstatsview.js
 js   js/admin/createuser.js
 js   js/admin/useradminsales.js
 js   js/admin/adminstats.js
 js   js/account/mailapi.js
 js   js/account/company.js
 js   js/account/user.js
 js   js/account/stats.js
 js   js/account/accountsettings.js
 js   js/account/securitysettings.js
 js   js/account/mailapisettings.js
 js   js/account/companyaccounts.js
 js   js/account/companybranding/companybrandingutils.js
 js   js/account/companybranding/companybrandingemail.js
 js   js/account/companybranding/companybrandingsignview.js
 js   js/account/companybranding/companybrandingservice.js
 js   js/account/companybranding/companybranding.js
 js   js/account/account.js
 js   js/blocking.js
 js   js/oauth.js

