
ignore  tiny_mce/tiny_mce.js
ignore  tiny_mce/tiny_mce_src.js
ignore  tiny_mce/tiny_mce_popup.js
ignore  tiny_mce/langs
ignore  tiny_mce/plugins
ignore  tiny_mce/themes
ignore  tiny_mce/utils
ignore  libs/analytics.js
ignore  libs/zenbox.js
ignore  js/signup.js
ignore  libs/recurly/recurly.css
ignore  api-demo


set firstPage
 css css/main.css
 css css/flash.css
 css css/symbols.css
 css css/newdesign.css
 css css/buttons.css
 js  libs/jquery.min.js
 js  libs/jquery-ui.min.js
 js  libs/jquery.tools.min.js
 js  libs/jquery.MultiFile.js
 jsx tiny_mce/jquery.tinymce.js
 js  libs/jquery.tweet.js
 js  libs/analytics.js
 js  libs/zenbox.js
 js  libs/underscore.js
 js  libs/backbone.js
 js  libs/jquery.form.js
 js  libs/json2.js
 js  js/global.js
 js  js/flashmessages.js
 js  js/validation.js
 js  js/submits.js
 js  js/infotextinputs.js
 js  js/buttons.js
 js  js/confirmations.js
 js  js/login.js

set systemPage
 css css/newdesign.css
 css css/designview.css
 css css/style.css
 css css/calendar.css
 css css/signaturedrawer.css
 css css/archive.css
 css css/symbols.css
 css css/tabs.css
 css css/lists.css
 css css/buttons.css
 css css/account.css
 css css/flash.css
 css css/docsignview.css
 css css/main.css
 css css/createfromtemplate.css
 less less/selects.less
 less less/document-pages.less
 less less/payments.less
 less less/paymentsoutside.less
 less less/oauth.less
 less less/arrows.less
 less less/blocking.less
 js   libs/jquery.min.js
 js   libs/jquery-ui.min.js
 js   libs/jquery.tools.min.js
 js   libs/jquery.MultiFile.js
 jsx  tiny_mce/jquery.tinymce.js
 js   libs/json2.js
 js   libs/jstz.min.js
 js   libs/underscore.js
 js   libs/backbone.js
 js   libs/jquery.form.js
 js   libs/livequery.js
 js   libs/recurly.js
 js   libs/moment.min.js
 js   libs/iso8601.min.js
 js   js/global.js
 js   js/storage.js
 js   js/browserinfo.js
 js   js/loading.js
 js   js/table.js
 js   js/arrows.js
 js   js/flashmessages.js
 js   js/infotextinputs.js
 js   js/buttons.js
 js   js/uploadbuttons.js
 js   js/tooltips.js
 js   js/calendar.js
 js   js/submits.js
 js   js/ajaxqueue.js
 js   js/confirmations.js
 js   js/selects.js
 js   js/login.js
 js   js/lists/action.js
 js   js/lists/sorting.js
 js   js/lists/filtering.js
 js   js/lists/paging.js
 js   js/lists/schema.js
 js   js/lists/lists.js
 js   js/tabs.js
 js   js/files.js
 js   js/process.js
 js   js/fields.js
 js   js/signature.js
 js   js/signatories.js
 js   js/documents.js
 js   js/confirmationsWithEmails.js
 js   js/docview.js
 js   js/attachmentview.js
 js   js/tasks.js
 js   js/docsignviewframes.js
 js   js/signview/docsignviewinstructions.js
 js   js/signview/docsignviewsignatories.js
 js   js/signview/docsignviewcreateaccount.js
 js   js/signview/docsignviewpromotescrive.js
 js   js/signview/docsignviewextradetailssection.js
 js   js/signview/docsignviewsignsection.js
 js   js/signview/docsignviewpad.js
 js   js/signview/docsignview.js
 js   js/signatorydesignview.js
 js   js/docdesignviewpad.js
 js   js/docdesignview.js
 js   js/mobilebankid.js
 js   js/bankid.js
 js   js/createfromtemplate/createfromtemplate.js
 js   js/attachmentsdesignview.js
 js   js/csvsignatorydesign.js
 js   js/validation.js
 js   js/signaturedrawer.js
 js   js/fieldplacementview.js
 js   js/padview.js
 js   js/fileverifier.js
 js   js/payments.js
 js   js/archive/documents.js
 js   js/archive/templates.js
 js   js/archive/attachments.js
 js   js/archive/bin.js
 js   js/archive/archive.js
 js   js/account/mailapi.js
 js   js/account/company.js
 js   js/account/user.js
 js   js/account/stats.js
 js   js/account/accountsettings.js
 js   js/account/securitysettings.js
 js   js/account/mailapisettings.js
 js   js/account/companyaccounts.js
 js   js/account/companybranding.js
 js   js/account/account.js
 js   js/blocking.js
 js   js/oauth.js

