---
$schema: "http://json-schema.org/draft-04/schema#"
title: UserGroupSettings
type: object
example: {
  "inherited_from": null,
  "data_retention_policy": {
    "idle_doc_timeout_preparation": null,
    "idle_doc_timeout_closed": null,
    "idle_doc_timeout_canceled": 42,
    "idle_doc_timeout_timedout": null,
    "idle_doc_timeout_rejected": null,
    "idle_doc_timeout_error": null,
    "immediate_trash": false
  }
}
description: |
  JSON representation of a User Group's Settings.
properties:
  inherited_from:
    type: string
  data_retention_policy:
    type: object
    properties:
      idle_doc_timeout_preparation:
        type: integer
        description: |
          Number of days to retain the document after preparation
      idle_doc_timeout_closed:
        type: integer
        description: |
          Number of days to retain the document after closed
      idle_doc_timeout_canceled:
        type: integer
        description: |
          Number of days to retain the document after canceled
      idle_doc_timeout_timedout:
        type: integer
        description: |
          Number of days to retain the document after timedout
      idle_doc_timeout_rejected:
        type: integer
        description: |
          Number of days to retain the document after rejected
      idle_doc_timeout_error:
        type: integer
        description: |
          Number of days to retain the document after error
      immediate_trash:
        type: boolean
