# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "call-me-maybe-1.0.1" = {
      name = "call-me-maybe";
      packageName = "call-me-maybe";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-me-maybe/-/call-me-maybe-1.0.1.tgz";
        sha1 = "26d208ea89e37b5cbde60250a15f031c16a4d66b";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "core-js-2.6.11" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.6.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.6.11.tgz";
        sha512 = "5wjnpaT/3dV+XB4borEsnAYQchn00XSgTAWKDkEqv+K8KevjbzmofK6hfJ9TZIlpj2N0xQpazy7PiRQiWHqzWg==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-3.2.6" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.6.tgz";
        sha512 = "mel+jf7nrtEl5Pn1Qx46zARXKDpBbvzezse7p7LqINmdoIk8PYP5SySaxEmYv6TZ0JyEKA1hsCId6DIhgITtWQ==";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "es6-promise-3.3.1" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-3.3.1.tgz";
        sha1 = "a08cdde84ccdbf34d027a1451bc91d4bcd28a613";
      };
    };
    "es6-promise-4.2.8" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-4.2.8.tgz";
        sha512 = "HJDGx5daxeIvxdBxvG2cb9g4tEvwIk3i8+nhX0yGrYmZUzbkdg8QbDevheDB8gd0//uPj4c1EQua8Q+MViT0/w==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "format-util-1.0.5" = {
      name = "format-util";
      packageName = "format-util";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/format-util/-/format-util-1.0.5.tgz";
        sha512 = "varLbTj0e0yVyRpqQhuWV+8hlePAgaoFRhNFj50BNjEIrw1/DphHSObtqwskVCPWNgzwPoQrZAbfa/SBiicNeg==";
      };
    };
    "fs-0.0.2" = {
      name = "fs";
      packageName = "fs";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs/-/fs-0.0.2.tgz";
        sha1 = "e1f244ef3933c1b2a64bd4799136060d0f5914f8";
      };
    };
    "js-yaml-3.14.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.0.tgz";
        sha512 = "/4IbIeHcD9VMHFqDR/gQ7EdZdLimOvW2DdcxFjdyyZ9NsbS+ccrXqVWDtab/lRl5AlUqmpBx8EhPaWR+OtY17A==";
      };
    };
    "json-schema-ref-parser-1.4.1" = {
      name = "json-schema-ref-parser";
      packageName = "json-schema-ref-parser";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-ref-parser/-/json-schema-ref-parser-1.4.1.tgz";
        sha1 = "c0c2e438bf0796723b02451bae8bc7dd0b37fed0";
      };
    };
    "json-schema-ref-parser-3.3.1" = {
      name = "json-schema-ref-parser";
      packageName = "json-schema-ref-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-ref-parser/-/json-schema-ref-parser-3.3.1.tgz";
        sha512 = "stQTMhec2R/p2L9dH4XXRlpNCP0mY8QrLd/9Kl+8SHJQmwHtE1nDfXH4wbsSM+GkJMl8t92yZbI0OIol432CIQ==";
      };
    };
    "linkify-it-2.2.0" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-2.2.0.tgz";
        sha512 = "GnAl/knGn+i1U/wjBz3akz2stz+HrHLsxMwHQGofCDfPvlf+gDKN58UtfmUquTY4/MXeE2x7k19KQmeoZi94Iw==";
      };
    };
    "lodash-4.17.20" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.20.tgz";
        sha512 = "PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA==";
      };
    };
    "lodash.get-4.4.2" = {
      name = "lodash.get";
      packageName = "lodash.get";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.get/-/lodash.get-4.4.2.tgz";
        sha1 = "2d177f652fa31e939b4438d5341499dfa3825e99";
      };
    };
    "lodash.isequal-4.5.0" = {
      name = "lodash.isequal";
      packageName = "lodash.isequal";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.5.0.tgz";
        sha1 = "415c4478f2bcc30120c22ce10ed3226f7d3e18e0";
      };
    };
    "markdown-it-7.0.1" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-7.0.1.tgz";
        sha1 = "f12d8b88a93e64254348dfd183bd70bf60567a42";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "ono-2.2.5" = {
      name = "ono";
      packageName = "ono";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ono/-/ono-2.2.5.tgz";
        sha1 = "daf09488b51174da7a7e4275dfab31b438ffa0e3";
      };
    };
    "ono-4.0.11" = {
      name = "ono";
      packageName = "ono";
      version = "4.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ono/-/ono-4.0.11.tgz";
        sha512 = "jQ31cORBFE6td25deYeD80wxKBMj+zBmHTrVxnc6CKhx8gho6ipmWM5zj/oeoqioZ99yqBls9Z/9Nss7J26G2g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "swagger-methods-1.0.8" = {
      name = "swagger-methods";
      packageName = "swagger-methods";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/swagger-methods/-/swagger-methods-1.0.8.tgz";
        sha512 = "G6baCwuHA+C5jf4FNOrosE4XlmGsdjbOjdBK4yuiDDj/ro9uR4Srj3OR84oQMT8F3qKp00tYNv0YN730oTHPZA==";
      };
    };
    "swagger-parser-3.4.2" = {
      name = "swagger-parser";
      packageName = "swagger-parser";
      version = "3.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/swagger-parser/-/swagger-parser-3.4.2.tgz";
        sha512 = "himpIkA50AjTvrgtz0PPbzwWoTjj3F3ye/y1PcW/514YEp1A3IhAcJFkkEu7b1zHnSIthnzxC8aTy+XZG0D+iA==";
      };
    };
    "swagger-schema-official-2.0.0-bab6bed" = {
      name = "swagger-schema-official";
      packageName = "swagger-schema-official";
      version = "2.0.0-bab6bed";
      src = fetchurl {
        url = "https://registry.npmjs.org/swagger-schema-official/-/swagger-schema-official-2.0.0-bab6bed.tgz";
        sha1 = "70070468d6d2977ca5237b2e519ca7d06a2ea3fd";
      };
    };
    "uc.micro-1.0.6" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.6.tgz";
        sha512 = "8Y75pvTYkLJW2hWQHXxoqRgV7qb9B+9vFEtidML+7koHUFapnVJAZ6cKs+Qjz5Aw3aZWHMC6u0wJE3At+nSGwA==";
      };
    };
    "validator-10.11.0" = {
      name = "validator";
      packageName = "validator";
      version = "10.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-10.11.0.tgz";
        sha512 = "X/p3UZerAIsbBfN/IwahhYaBbY68EN/UQBWHtsbXGT5bfrH/p4NQzUCG1kF/rtKaNpnJ7jAu6NGTdSNtyNIXMw==";
      };
    };
    "z-schema-3.25.1" = {
      name = "z-schema";
      packageName = "z-schema";
      version = "3.25.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/z-schema/-/z-schema-3.25.1.tgz";
        sha512 = "7tDlwhrBG+oYFdXNOjILSurpfQyuVgkRe3hB2q8TEssamDHB7BbLWYkYO98nTn0FibfdFroFKDjndbgufAgS/Q==";
      };
    };
  };
in
{
  openapi2slate = nodeEnv.buildNodePackage {
    name = "openapi2slate";
    packageName = "openapi2slate";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/openapi2slate/-/openapi2slate-1.0.1.tgz";
      sha512 = "RhFK5wtVSszDToy+v49mg2xUdVtkBdefTm+l71uwBB/25ZPAPS1dt9mdOwRMErtFPb5h1P8iJgB8+r+fWpgk7w==";
    };
    dependencies = [
      sources."argparse-1.0.10"
      sources."call-me-maybe-1.0.1"
      sources."commander-2.20.3"
      sources."core-js-2.6.11"
      sources."debug-3.2.6"
      sources."entities-1.1.2"
      sources."es6-promise-4.2.8"
      sources."esprima-4.0.1"
      sources."format-util-1.0.5"
      sources."fs-0.0.2"
      sources."js-yaml-3.14.0"
      sources."json-schema-ref-parser-3.3.1"
      sources."linkify-it-2.2.0"
      sources."lodash-4.17.20"
      sources."lodash.get-4.4.2"
      sources."lodash.isequal-4.5.0"
      sources."markdown-it-7.0.1"
      sources."mdurl-1.0.1"
      sources."ms-2.1.2"
      sources."ono-4.0.11"
      sources."sprintf-js-1.0.3"
      sources."swagger-methods-1.0.8"
      (sources."swagger-parser-3.4.2" // {
        dependencies = [
          (sources."json-schema-ref-parser-1.4.1" // {
            dependencies = [
              sources."debug-2.6.9"
              sources."es6-promise-3.3.1"
              sources."ono-2.2.5"
            ];
          })
          sources."ms-2.0.0"
        ];
      })
      sources."swagger-schema-official-2.0.0-bab6bed"
      sources."uc.micro-1.0.6"
      sources."validator-10.11.0"
      sources."z-schema-3.25.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Convert an Open API (i.e. Swagger) specification to Slate Markdown";
      homepage = https://github.com/scrive/openapi2slate;
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}