###
simpliefiedTextNewDocumentEvidence          = $_simpliefiedTextNewDocumentEvidence()$
###
simpliefiedTextRestartDocumentEvidence      = $_simpliefiedTextRestartDocumentEvidence()$
###
simpliefiedTextPreparationToPendingEvidence = $_simpliefiedTextPreparationToPendingEvidence()$
###
simpliefiedTextCloseDocumentEvidence        = $_simpliefiedTextCloseDocumentEvidence()$
###
simpliefiedTextCancelDocumentEvidence       = $_simpliefiedTextCancelDocumentEvidence()$
###
simpliefiedTextRejectDocumentEvidence       = $_simpliefiedTextRejectDocumentEvidence()$
###
simpliefiedTextTimeoutDocumentEvidence      = $_simpliefiedTextTimeoutDocumentEvidence()$
###
simpliefiedTextMarkInvitationReadEvidence   = $_simpliefiedTextMarkInvitationReadEvidence()$
###
simpliefiedTextMarkDocumentSeenEvidence     = $_simpliefiedTextMarkDocumentSeenEvidence()$
####
simpliefiedTextSignDocumentEvidence         = $_simpliefiedTextSignDocumentEvidence()$
####
simpliefiedTextInvitationEvidence           = $_simpliefiedTextInvitationEvidence()$
####
simpliefiedTextInvitationDelivered          = $_simpliefiedTextInvitationDelivered()$
#####
simpliefiedTextInvitationUndelivered        = $_simpliefiedTextInvitationUndelivered()$
#####
simpliefiedTextReminderSend                 = $_simpliefiedTextReminderSend()$
#####
simpliefiedTextResealedPDF                  = $_simpliefiedTextResealedPDF()$
#####
simpliefiedTextCancelDocumenElegEvidence    = $_simpliefiedTextCancelDocumenElegEvidence()$
##### UTILS
#####
notNamedParty = $_notNamedParty()$
#####
authorParty = $_authorParty()$
#####
#####

