###
simpliefiedTextNewDocumentEvidence           = Document created
###
simpliefiedTextRestartDocumentEvidence       = Document created
###
simpliefiedTextPreparationToPendingEvidence  = Document send 
###
simpliefiedTextCloseDocumentEvidence        = Document closed and stamped by Scrive
###
simpliefiedTextCancelDocumentEvidence       = Document canceled
###
simpliefiedTextRejectDocumentEvidence       = Document rejected
###
simpliefiedTextTimeoutDocumentEvidence      = Document timeouted
###
simpliefiedTextMarkInvitationReadEvidence   = Document invitation read
###
simpliefiedTextMarkDocumentSeenEvidence     = Document seen online
####
simpliefiedTextSignDocumentEvidence         = Document signed
#####
##### UTILS
#####
notNamedParty = $_notNamedParty()$
#####
authorParty = $_authorParty()$
#####
#####

