###
simpliefiedTextNewDocumentEvidence          = Created document. It is ready to be signed.
###
simpliefiedTextRestartDocumentEvidence      = Created document. It is ready to be signed.
###
simpliefiedTextPreparationToPendingEvidence = Created document. It is ready to be signed.
###
simpliefiedTextCloseDocumentEvidence        = Document closed and stamped by Scrive
###
simpliefiedTextCancelDocumentEvidence       = Document canceled
###
simpliefiedTextRejectDocumentEvidence       = Document rejected
###
simpliefiedTextTimeoutDocumentEvidence      = Document timeouted
###
simpliefiedTextMarkInvitationReadEvidence   = Document invitation read
###
simpliefiedTextMarkDocumentSeenEvidence     = Document seen online
####
simpliefiedTextSignDocumentEvidence         = Document signed
####
simpliefiedTextInvitationEvidence           = Invitation send to $affectedsignatory$ $if(text)$ with message $text:noescape()$ $endif$.
####
simpliefiedTextInvitationDelivered          = Invitation delivered to $affectedsignatory$.
#####
simpliefiedTextInvitationUndelivered        = Invitation could not be delivered to $affectedsignatory$.
#####
simpliefiedTextReminderSend                 = Reminder send to $affectedsignatory$ $if(text)$ with message $text:noescape()$ $endif$.
#####
simpliefiedTextResealedPDF                  = Document resealed by Scrive admin
#####
simpliefiedTextCancelDocumenElegEvidence    = Cancelled document due to signatory and elegitimation data mismatch
##### UTILS
#####
notNamedParty = $_notNamedParty()$
#####
authorParty = $_authorParty()$
#####
#####

