/**
 *  @description
 *  Generate a unique hex string, from specified enviroment variables
 *
 *  @note
 *  This function exists in kontraktcja (haskell) too. 
 *  The generated string is used to know which 'versioned' static files to load
 *
 *  Example: 
 *  dist/optimized.js -> 214213321as123-optimized.js
 *  
 *  where 214213321as123 is the string generated by this function
 */
var generateVersionId = function() {
  var variables = {
    build_date: process.env.BUILD_DATE,
    build_number: process.env.BUILD_NUMBER,
    build_vcs_number: process.env.BUILD_VCS_NUMBER,
  };

  var lst = [];
  for(var property in variables) {
    if(typeof variables[property] !== 'string') {
      lst.push(property);
    } else {
      lst.push(variables[property]);
    }
  }
  var stringToEncode = lst.join('.');

  var hexEncodedString = new Buffer(stringToEncode).toString('hex');
  return hexEncodedString;
};

module.exports = generateVersionId;
