#####
contractsealingtexts=
SealingTexts
    {   verificationTitle="$_contractsealingtexts()$"
      , docPrefix="$_sealingtextsdocPrefix()$"
      , signedText="$_contractsealingtextssignedText()$"
      , partnerText="$_contractsealingtextspartnerText()$"
      , secretaryText="$_contractsealingtextssecretaryText()$"
      , documentText="$_documentText()$"
      , orgNumberText="$_contractsealingtextsorgNumberText()$"
      , personalNumberText="$_personalNumberText()$"
      , eventsText="$_contractsealingtextseventsText()$"
      , dateText="$_contractsealingtextsdateText()$"
      , historyText="$_contractsealingtextshistoryText()$"
      , verificationFooter="$_verificationFooter()$"
      , hiddenAttachmentText="$_contractsealingtextshiddenAttachment()$"
      , onePageText="$_numberOfPagesIs1()$"
    }
#####
