tbs= Du undertecknar "$documentname$" med transaktionsnummer "$documentnumber$". Undertecknande parter är:
$tbssigentries$
##
tbssig=  $firstname$ $lastname$, $number$

##
signCanceledDataMismatch=
    <div class="centerdivnarrow">
      <p class="headline">Felaktiga personuppgifter</p>

      <p>Vi beklagar. Uppgifterna i din e-legitimation matchar inte dina personuppgifter.</p>

      $cancelationMessage$

    </div>
##
