tbs=$_tbsYouSignWithEleg()$
##
tbssig=  $firstname$ $lastname$, $number$

##
signCanceledDataMismatch=
    <div class="centerdivnarrow">
      <p class="headline">$_signCanceledDataMismatchIncorrectPersonalInfo()$</p>

      <p>$_signCanceledDataMismatchBody()$</p>

      $cancelationMessage$

    </div>
##
bankidInvalidParameters=$_bankidInvalidParameters()$
##
bankidInternalError=$_bankidInternalError()$
##
bankidUnknownUser=$_bankidUnknownUser()$
##
bankidExpiredTransaction=$_bankidExpiredTransaction()$
##
bankidInvalidDevices=$_bankidInvalidDevices()$
##
bankidAlreadyInProgress=$_bankidAlreadyInProgress()$
##
bankidUserCancel=$_bankidUserCancel()$
##
bankidEnterCode=$_bankidEnterCode()$
##
bankidStartApp=$_bankidStartApp()$
##
bankidPersInfoMismatch=$_bankidPersInfoMismatch()$: $message$
##
bankidVerificationFailed=$_bankidVerificationFailed()$
##
bankidNoFirstName=$_bankidNoFirstName()$
##
bankidFirstNameMismatch=$_bankidFirstNameMismatch()$: '$contract$' $_and()$ '$eleg$'.
##
bankidNoLastName=$_bankidNoLastName()$
##
bankidLastNameMismatch=$_bankidLastNameMismatch()$: '$contract$' $_and()$ '$eleg$'.
##
bankidNoNumber=$_bankidNoNumber()$
##
bankdiNumberMismatch=$_bankidNumberMismatch()$: '$contract$' $_and()$ '$eleg$'.
##