tbs=$_tbsYouSignWithEleg()$
##
tbssig=  $firstname$ $lastname$, $number$

##
bankidInvalidParameters=$_bankidInvalidParameters()$
##
bankidInternalError=$_bankidInternalError()$
##
bankidUnknownUser=$_bankidUnknownUser()$
##
bankidExpiredTransaction=$_bankidExpiredTransaction()$
##
bankidInvalidDevices=$_bankidInvalidDevices()$
##
bankidAlreadyInProgress=$_bankidAlreadyInProgress()$
##
bankidUserCancel=$_bankidUserCancel()$
##
bankidEnterCode=$_bankidEnterCode()$
##
bankidStartApp=$_bankidStartApp()$
##
bankidVerificationFailed=$_bankidVerificationFailed()$
##