### Some comment here
flashDocumentDraftSaved= <div>
     Du har sparat dokumentet.
    </div>
######
flashRemindMailSentNotSigned=En påminnelse har skickats till $personname$
######
flashRemindMailSentSigned=Dokumentet har skickats till $personname$
######
flashMessageCanceled=<span>Du har nu återkallat inbjudan att underteckna dokumentet och ett meddelande om återkallelsen har skickats till samtliga parter.</span>
#####
flashMessageMustAcceptTOS=För att kunna använda tjänsten måste du acceptera SkrivaPå Allmänna Villkor.
####
flashMessageUserDetailsSaved=<div>Dina kontoändringar har sparats.</div>
####
flashMessagePasswordNotStrong=Det nya lösenordet ska vara minst 6 tecken
####        
flashMessageBadOldPassword=Du har skrivit in fel nuvarande lösenord
####
flashMessagePasswordsDontMatch="Nytt lösenord" matchar inte med "Upprepa lösenord" 
###
flashDocumentRestarted=Du har startat om dokumentet och kan nu underteckna och skicka inbjudan på nytt.
###
flashMessageUserPasswordChanged=Lösenord ändrat
###
flashMessagePasswordChangeLinkNotValid=Vi beklagar. Länken är inte längre giltig.<BR/> Vänligen använd "Glömt lösenord" för att generera en ny länk.
###
flashMessageUserWithSameEmailExists=En användare med samma e-post existerar redan.
###
flashMessageActivationLinkNotValid=Vi beklagar. Länken är inte längre giltig.<BR/> Vänligen använd "Glömt lösenord" för att generera en ny länk.
###
