### 
restartButtonName=Starta om dokument
######
uploadPageContent=
  <div class="centerdivnarrow" style="margin-top: 100px;">
   <form action="/d" method="post" enctype="multipart/form-data">
    <span class="small">Välj dokument (endast PDF)</span><br/>
    <input class="multi" maxlength="1" type="file" name="doc" accept="application/pdf"/>
    <input class="bigbutton" type="submit" value="Ladda upp"/>
   </form>
  </div>

####
firstPageContent=
 <div>
    <div id="firstPageLeft">
         <h1>Snabbt, smidigt och säkert</h1>
         <p>SkrivaPå är en tjänst för elektronisk signering och arkivering. Spara tid och minska onödiga kostnader med enklare och smidigare avtalshantering. Skapa ett konto gratis och testa tjänsten redan idag! Vi bjuder på de 5 första avtalen.</p>
         <p><a href="$signuplink$" class="button">Skapa konto</a></p>
    </div>
    <div id="firstPageRight">
         <object>
             <embed src="https://secure.vimeo.com/moogaloop.swf?clip_id=17638316&server=vimeo.com&show_title=0&show_byline=0&show_portrait=0&color=00ADEF&fullscreen=1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="520" height="319">
             </embed>
         </object>
     </div>
 </div>

