unsupportedBrowser=
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>$_unsupportedBrowserTitle()$</title>
    <meta http-equiv="content-language" content="en" />
    <style media="screen" type="text/css">
      @font-face {
        font-family: "Helvetica Neue";
        src: url("/fonts/HelveticaNeue.eot");
      }
    </style>
  </head>
  <body style="background-color: #F7F7F7; font-family: 'Helvetica Neue';">

    <div style="width: 100%; min-height: 95px; border-top: 1px solid #dee4ed; border-bottom: 1px solid #dee4ed; margin-top: 3px; background-color: #FFFFFF;">
      <div style="width: 960px; margin: 0 auto; vertical-align: middle; min-height: 99px;">
        <a href="/">
          <img src="/img/logo-white-bg.png" width="120" height="22" style="margin: 27px 0 26px; padding-top: 10px; padding-bottom: 10px; border: 0;" />
        </a>
      </div>
    </div>

    <div style="margin: 0 auto; width: 550px; margin-top: 112px;">
      <div style="text-align: center; margin-bottom: 26px; font-size: 72pt; letter-spacing: -20; color: #D9D9D9;">
        $_unsupportedBrowserSorry()$
      </div>
      <div style="text-align: center; font-size: 14.5pt; letter-spacing: -20; color: #4D4D4D;">
        $_unsupportedBrowserHeader()$
      </div>
      <div style="text-align: center; font-size: 18pt; letter-spacing: -20; color: #4D4D4D; margin-bottom: 14px;">
        Internet Explorer 6
      </div>
      <div style="margin-bottom: 50px;">
        <center>
          <img src="/img/IE-logo-circle.png"/>
        </center>
      </div>
      <div style="margin-bottom: 18px; font-size: 14.5pt; letter-spacing: -20; color: #4D4D4D;">
        $_unsupportedBrowserInstructionsHeader()$
      </div>
      <div style="font-size: 14.5pt; letter-spacing: -20; color: #4D4D4D;">
        <div>1. $_unsupportedBrowserInstruction1()$</div>
        <div>2. $_unsupportedBrowserInstruction2()$</div>
      </div>
    </div>

  </body>
</html>
