---
swagger: '2.0'

info:
  title: Scrive User API
  description: |
    # TODO General Description
  version: 2.0.0
  contact:
    name: Scrive AB
    url: https://scrive.com/
    email: info@scrive.com
  termsOfService: |
    In using this API you agree to be bound by the Scrive Terms of Service,
    available at [http://scrive.com/en/terms](http://scrive.com/en/terms)
  license:
    name: All Rights Reserved

host: scrive.com

basePath: /api/v2

schemes:
  - https

tags:
  - name: User
  - name: Internal

paths:

# TODO

#  /getpersonaltoken:
#    # hPost $ toK0 $ apiCallGetUserPersonalToken,
  /signup:
    # hPost $ toK0 $ apiCallSignup,
    post:
      summary: Signup Request
      tags:
        - User
      description: |
        **TODO Proper description**

        Response will be one of:

        * `{"sent":true}`
        * `{"sent":false}`
      parameters:
        - name: email
          in: formData
          type: email
          required: true
          description: TODO
        - name: firstName
          in: formData
          type: string
          required: false
          description: TODO
        - name: lastName
          in: formData
          type: string
          required: false
          description: TODO
        - name: lang
          in: formData
          required: false
          description: TODO Has to be a valid lang code
          #$ref: ./definitions/LanguageCode.yaml
      responses:
        200:
          description: TODO
#  /login:
#    # hPostNoXToken $ toK0 $ apiCallLoginUser,
#  /sendpasswordresetmail:
#    # hPost $ toK0 $ apiCallSendPasswordReminder,
#  /getprofile:
#    # hGet $ toK0 $ apiCallGetUserProfile,
#  /changepassword:
#    # hPost $ toK0 $ apiCallChangeUserPassword,
#  /updateprofile:
#    # hPost $ toK0 $ apiCallUpdateUserProfile,
#  /changeemail:
#    # hPost $ toK0 $ apiCallChangeEmail,
#  /addflash:
#    # hPost $ toK0 $ apiCallAddFlash,
#  /paymentinfo:
#    # hGet $ toK0 $ apiCallPaymentInfo,
#  /getcallbackscheme:
#    # hGet $ toK0 $ apiCallUserGetCallbackScheme,
#  /testsalesforceintegration:
#    # hGet $ toK0 $ apiCallTestSalesforceIntegration
#  /loginandgetsession:
#    # hPost $ toK0 $ apiCallLoginUserAndGetSession

  /loginandgetsession:
    # hPost $ toK0 $ apiCallLoginUserAndGetSession
    post:
      summary: Login User And Get Session
      tags:
        - User
      description: |
        This call allows creation of a link, which leads user directly to
        any page on scrive.com without going through the login page. This
        creates better user experience.

        Login user using his OAuth tokens. The tokens have to be acquired
        by /api/v2/getpersonaltoken.

        The call the returns a session id, which can be used to create a link like
        `https://scrive.com/loginwithredirect?session_id=SESSION_ID&url=PATH_INSIDE_SCRIVE_COM`.

      parameters:
        - name: json
          in: formData
          type: object
          format: application/json
          required: true
          description: |
            For example:

            ```json
            {
              "apitoken" : "987dfsd312sd76sh_123"
            , "apisecret" : "c47b87126dsacbhb"
            , "accesstoken" : "2d1287dassg22jke_114"
            , "accesssecret" : "12876adsdhght665"
            }
            ```

      responses:
        200:
          description: |
            For example:

            ```json
            {
              "status" : "ok"
            , "session_id" : "45468-a2510867954321d0"
            }
            ```

            In case of error:

            ```json
            {
              "status" : "error"
            , "error_message" .= "some error message for humans"
            }

definitions:
  Lang:
    $ref: ./definitions/LanguageCode.yaml
#parameters:
#responses:
