jobs:
  frontend-tests:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"
      - name: Setup Cachix
        uses: "cachix/cachix-action@v6"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: scrive
      - env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        name: Setup SSH
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      - name: Load Nix Shell
        run: |
          nix-shell -j8 --arg extra-run-deps "pkgs: hsPkgs: [ pkgs.chromium ]" \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "echo Loaded Nix shell"
      - name: Test Frontend
        run: |
          nix-shell -j8 --arg extra-run-deps "pkgs: hsPkgs: [ pkgs.chromium ]" \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./ci/scripts/run-frontend-tests.sh"
name: Frontend Tests
on:
  pull_request: {}
  push:
    branches:
      - master
      - staging
      - production
