jobs:
  backend-tests:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"
      - name: Setup Cachix
        uses: "cachix/cachix-action@v6"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: scrive
      - env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        name: Setup SSH
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      - name: Load Nix Shell
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "echo Loaded Nix shell"
      - env:
          PDFTOOLS_CONFIG: "${{ secrets.PDFTOOLS_CONFIG }}"
        name: Run Backend Tests
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./ci/scripts/run-backend-tests.sh"
        timeout-minutes: 60
  detect-unused:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"
      - name: Setup Cachix
        uses: "cachix/cachix-action@v6"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: scrive
      - env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        name: Setup SSH
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      - name: Load Nix Shell
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "echo Loaded Nix shell"
      - name: Detect Old Templates
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./shake.sh detect-old-templates"
      - name: Detect Old Localizations
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./shake.sh detect-old-localizations"
  formatting:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"
      - name: Setup Cachix
        uses: "cachix/cachix-action@v6"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: scrive
      - env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        name: Setup SSH
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      - name: Load Nix Shell
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "echo Loaded Nix shell"
      - name: Test Formatting
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./shake.sh test-formatting"
  hlint:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"
      - name: Setup Cachix
        uses: "cachix/cachix-action@v6"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: scrive
      - env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        name: Setup SSH
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      - name: Load Nix Shell
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "echo Loaded Nix shell"
      - name: Test HLint
        run: |
          nix-shell -j8 \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./shake.sh hlint"
name: "GHC 8.8 Backend Tests (Nix)"
on:
  pull_request: {}
  push:
    branches:
      - master
      - staging
      - production
