jobs:
  backend-tests:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"
      - name: Setup Cachix
        uses: "cachix/cachix-action@v6"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: scrive
      - env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        name: Setup SSH
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      - name: Load Nix Shell
        run: |
          nix-shell -j8 \
            -A ghc88.manual-shell \
            release.nix \
            --run "echo Loaded Nix shell"
      - name: "Cache ~/.cabal"
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-cabal-backend-tests-${{ hashFiles('**/*.cabal') }}"
          path: "~/.cabal"
          restore-keys: |
            ${{ runner.os }}-cabal-backend-tests-${{ hashFiles('**/*.cabal') }}
            ${{ runner.os }}-cabal-backend-tests-
      - name: Build Kontrakcja
        run: |
          nix-shell -j8 \
            -A ghc88.manual-shell \
            release.nix \
            --run "cabal update; cabal configure --enable-tests --disable-optimization; cabal build all"
        timeout-minutes: 180
      - env:
          PDFTOOLS_CONFIG: "${{ secrets.PDFTOOLS_CONFIG }}"
        name: Run Backend Tests
        run: |
          nix-shell -j8 \
            -A ghc88.manual-shell \
            release.nix \
            --run "./ci/scripts/run-backend-tests.sh"
        timeout-minutes: 180
      - if: "${{ always() }}"
        name: Upload Logs
        uses: "actions/upload-artifact@v2"
        with:
          name: logs
          path: logs
name: "GHC 8.8 Backend Tests (Manual)"
on:
  push:
    branches:
      - master
