jobs:
  formatting:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: Setup Nix
        uses: "cachix/install-nix-action@v10"
      - name: Setup Cachix
        uses: "cachix/cachix-action@v6"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: scrive
      - env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        name: Setup SSH
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      - name: Load Nix Shell
        run: |
          nix-shell -j8 --arg extra-run-deps 'pkgs: hsPkgs: [ pkgs.git ]' \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "echo Loaded Nix shell"
      - env:
          quick: "-quick"
        if: "${{ always() }}"
        name: Test HLint
        run: |
          nix-shell -j8 --arg extra-run-deps 'pkgs: hsPkgs: [ pkgs.git ]' \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./ci/scripts/test-hlint.sh"
      - env:
          quick: "-quick"
        name: Test Formatting
        run: |
          nix-shell -j8 --arg extra-run-deps 'pkgs: hsPkgs: [ pkgs.git ]' \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./ci/scripts/test-formatting.sh"
      - if: "${{ always() }}"
        name: Detect Old Templates
        run: |
          nix-shell -j8 --arg extra-run-deps 'pkgs: hsPkgs: [ pkgs.git ]' \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./shake.sh detect-old-templates"
      - if: "${{ always() }}"
        name: Detect Old Localizations
        run: |
          nix-shell -j8 --arg extra-run-deps 'pkgs: hsPkgs: [ pkgs.git ]' \
            -A ghc88.dev-shell-optimized \
            release.nix \
            --run "./shake.sh detect-old-localizations"
      - if: "${{ failure() }}"
        name: Upload Formatting Patch
        uses: "actions/upload-artifact@v2"
        with:
          name: formatting-patch
          path: "_build/formatting.patch"
name: Quick Formatting Tests
on:
  pull_request:
    paths:
      - "**.hs"
